# Generated by Django 3.0.7 on 2020-08-06 00:32

from django.db import migrations, models
import taxcategs.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='decision',
        ),
        migrations.AddField(
            model_name='categoryterm',
            name='decision',
            field=models.CharField(blank=True, choices=[(taxcategs.models.DecisionChoice['OK'], 'Accepted'), (taxcategs.models.DecisionChoice['KO'], 'Refused'), (taxcategs.models.DecisionChoice['KK'], 'Accepted with changes')], max_length=30),
        ),
    ]
