# Generated by Django 3.0.7 on 2020-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='formats_supported',
            field=models.ManyToManyField(blank=True, null=True, to='taxcategs.InputFormatSupported'),
        ),
    ]
