# Generated by Django 3.0.7 on 2020-08-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='decision',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Refused'), (3, 'Accepted with changes')], default=0),
        ),
    ]
