# Generated by Django 3.0.7 on 2020-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0002_auto_20200806_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='decision',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Accepted'), ('2', 'Refused'), ('3', 'Accepted with changes')], default='0', max_length=5),
        ),
    ]
