# Generated by Django 3.0.7 on 2020-07-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0002_auto_20200729_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='tax_categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxcategs.TaxCateg'),
        ),
    ]
