# Generated by Django 3.0.7 on 2020-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0003_auto_20200804_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryterm',
            name='substitute_tax_categ',
            field=models.BooleanField(default=False),
        ),
    ]
