# Generated by Django 3.0.7 on 2020-08-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0003_auto_20200806_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='decision',
            field=models.CharField(blank=True, choices=[('1', 'Accepted'), ('2', 'Refused'), ('3', 'Accepted with changes')], max_length=5),
        ),
    ]
