# Generated by Django 3.0.7 on 2020-08-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0004_categoryterm_substitute_tax_categ'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='categ_term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='taxcategs.CategoryTerm', verbose_name='Proposal reviewed'),
            preserve_default=False,
        ),
    ]
