# Generated by Django 3.0.7 on 2020-08-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0004_auto_20200806_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='term',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
