# Generated by Django 3.0.7 on 2020-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0005_auto_20200806_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryterm',
            name='term',
            field=models.CharField(max_length=50),
        ),
    ]
