# Generated by Django 3.0.7 on 2020-08-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0006_auto_20200806_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='result',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'New category term'), (2, 'New taxonomic category'), (3, 'Taxonomic category proposal save as new category term'), (4, 'Taxonomic category edited')]),
        ),
    ]
