# Generated by Django 3.0.7 on 2020-08-08 14:39

from django.db import migrations, models
import django.db.models.deletion
import taxcategs.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0009_auto_20200806_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryterm',
            name='image',
            field=models.ImageField(blank=True, upload_to=taxcategs.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='categoryterm',
            name='tax_categ',
            field=models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxcategs.TaxCateg'),
        ),
        migrations.AlterField(
            model_name='report',
            name='result',
            field=models.CharField(blank=True, choices=[('1', 'New category term'), ('2', 'Taxonomic category proposal save as new category term'), ('3', 'New taxonomic category'), ('4', 'Taxonomic category replaced')], max_length=5),
        ),
    ]
