# Generated by Django 3.0.7 on 2020-08-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0010_auto_20200808_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category_term',
            field=models.ForeignKey(limit_choices_to={'active': True}, on_delete=django.db.models.deletion.CASCADE, to='taxcategs.CategoryTerm'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
