# Generated by Django 3.0.7 on 2020-08-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default='Avd. Reina Mercedes s/n', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Seville', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Spain', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='41012', max_length=120),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default='Spain', max_length=120),
        ),
    ]
