# Generated by Django 3.0.7 on 2020-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Reviewer'), (2, 'Provider'), (3, 'Developer'), (4, 'Administrator')], default=3)),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Last Name')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('superuser', models.BooleanField(default=False, verbose_name='Is Super User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
