# Generated by Django 3.0.7 on 2020-07-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reviewer'), (2, 'Provider'), (3, 'Developer')], null=True),
        ),
    ]
