# Generated by Django 3.0.7 on 2020-07-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Reviewer'), (2, 'Provider'), (3, 'Developer'), (4, 'Administrator')], default=3),
        ),
    ]
