# Generated by Django 3.0.7 on 2020-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0010_auto_20200808_1639'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='taxcategs.TaxCateg'),
        ),
    ]
