# Generated by Django 3.0.7 on 2020-07-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='taxcategs.TaxCateg'),
        ),
    ]
