# Generated by Django 3.0.7 on 2020-08-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0005_report_categ_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='taxcategs.TaxCateg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to=products.models.upload_image_path),
            preserve_default=False,
        ),
    ]
