# Generated by Django 3.0.7 on 2020-08-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20200805_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=private_storage.fields.PrivateFileField(default=0, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='File'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductsAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='products.Product', verbose_name='Bought products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'ProductsAvailable',
                'verbose_name_plural': 'ProductsAvailables',
            },
        ),
    ]
