# Generated by Django 3.0.7 on 2020-08-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxcategs', '0012_comment_created_at'),
        ('products', '0003_auto_20200809_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(limit_choices_to={'active': True}, to='taxcategs.TaxCateg'),
        ),
    ]
