# Generated by Django 3.0.7 on 2020-08-05 13:53

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200805_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='component',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='', verbose_name='Component'),
        ),
    ]
