# Generated by Django 3.0.7 on 2020-08-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200805_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsavailable',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product', verbose_name='Bought products'),
        ),
    ]
